spring.application.name=studentrecords

spring.data.mongodb.uri=mongodb://localhost:27017/student_records

server.port=8080

jwt.secret=MySuperSecretKeyForStudentRecordsApplication2026
jwt.expiration-ms=86400000